### ISSUE TITLE
Missing Zip Module

### ISSUE THREAD

**Issue by zimmermq** [richardlock/powershell-install-lineagemagiskpatchedbootimage#1]
> [2023-02-25 23:00:01+01] [INFO   ] Opening 'C:\Users\...\Downloads\powershell-install-lineagemagiskpatchedbootimage-main\...\lineage.zip'.
> [2023-02-25 23:00:01+01] [ERROR  ] Der Typ [System.IO.Compression.ZipFile] wurde nicht gefunden.

Adding "Add-Type -AssemblyName System.IO.Compression, System.IO.Compression.FileSystem" to line 125 fixes the issue.

**Comment by richardlock** [comment]
Thanks for the PR. Which version of PowerShell are you using? I didn't have this issue on mine. Hope the script worked ok for you after the change.
