### ISSUE TITLE
Wrong download URI

### ISSUE THREAD

**Issue by zimmermq** [richardlock/powershell-install-lineagemagiskpatchedbootimage#4]
It seems that the Download server for the lineage-builds has moved.
The new URI for the latest build is:
https://mirrorbits.lineageos.org/full/hotdog/20230606/lineage-20.0-20230606-nightly-hotdog-signed.zip

The calculation for the download URI in "Get-LineageBuildFile" must therefore be adjusted.

**Comment by richardlock** [comment]
Hi. Have you pulled the latest version? I changed the code to pull the image from the device over adb to avoid downloading from changing locations. It's working well with my device if you could please test.

https://github.com/richardlock/powershell-install-lineagemagiskpatchedbootimage/blob/6f4874ab631e6ae018154a2a6dee89131815d649/Install-LineageMagiskPatchedBootImage.ps1#L109-L114

**Comment by zimmermq** [comment]
You are absolutely right. I have not used the latest version.
Sorry about that.
