### ISSUE TITLE
Patched image not booting

### ISSUE THREAD

**Issue by jzazo** [richardlock/powershell-install-lineagemagiskpatchedbootimage#5]
Hi. I tried this method and everything ran smoothly, up to the boot. When it tried to boot it would return to bootloader all the time. I flashed a past patched boot image, and everything started working again.

I wonder, if the patch script has some options which are not set correctly. Could that be the case? Could that be fixed? Thanks.

**Comment by richardlock** [comment]
Hi Javier,

Do you have any more details about the process you went through please? I only have my phone to test with but it works every time for me. I use the LineageOS Updater to download and install the latest version, then reboot. Then I initiate this script which pulls the image from the phone over ADB, patches it, then flashes the phone. It then boots back into the patched version of LineageOS. Which device and recovery are you running?

**Comment by jzazo** [comment]
If the options for your phone are the same as mine, I can retry again next time an update comes along and report back.

**Comment by richardlock** [comment]
I'm using LineageOS 20 on a moto g(7) which I think has vbmeta a and b partitions based on `ls -l /dev/block/by-name`.

**Comment by richardlock** [comment]
I'm just patching using `adb -s $DeviceSerialNumber shell '/data/adb/magisk/boot_patch.sh' $sourceFilePath` but not running the optional vbmeta step `fastboot flash vbmeta --disable-verity --disable-verification vbmeta.img` as documented here: https://topjohnwu.github.io/Magisk/install.html#patching-images

It indicates that this can wipe data and it doesn't seem to be necessary on mine or other people's devices using the script. Happy to add some optional commands with switches if you can identify the issue.

**Comment by jzazo** [comment]
I tried again today, and again, the phone did not boot. But this time I patched the image manually and it didn't work either. So maybe the the magisk modules interfere with the update (kdrag0n/safetynet-fix and shamiko). Do you do anything to disable the modules before patching or updating?

**Comment by richardlock** [comment]
I also use kdrag0n/safetynet-fix and it works fine without disabling any modules, but I haven't tried with shamiko. That could be an issue. I'm happy to add some steps if you want to test manually disabling the module(s), running the steps in the script, then reenabling. It looks possible to disable and reenable the modules from the command line so should be scriptable if it is one of the modules causing the issue.

https://forum.xda-developers.com/t/q-a-about-magisk-command-line-terminal-emulator.3782007/

**Comment by jzazo** [comment]
Yes, I will try manually disabling them, and let you know how it goes on the next build.
